export const mlbTeamNameToAbbrev: Record<string, string> = {
  Angels: "LAA",
  Astros: "HOU",
  Athletics: "OAK",
  "Blue Jays": "TOR",
  Braves: "ATL",
  Brewrs: "MIL",
  Cardinals: "STL",
  Cubs: "CHC",
  "D-backs": "ARI",
  Dodgers: "LAD",
  Giants: "SF",
  Guardians: "CLE",
  Mariners: "SEA",
  Marlins: "MIA",
  Mets: "NYM",
  Nationals: "WSH",
  Orioles: "BAL",
  Padres: "SD",
  Phillies: "PHI",
  Pirates: "PIT",
  Rangers: "TEX",
  "Red Sox": "BOS",
  Rays: "TB",
  Reds: "CIN",
  Rockies: "COL",
  Royals: "KC",
  Tigers: "DET",
  Twins: "MIN",
  "White Sox": "CWS",
  Yankees: "NYY",
};
